python:
  - 2.7  # [win]
  - 3.5  # [win]
  # avoid spurious python build matrix on unix
  - 3.6  # [unix]
mpi:
  - nompi
  - mpich  # [unix]
  - openmpi  # [unix]

pin_run_as_build:
  mpich: x.x
  openmpi: x.x
