mpi:
  - nompi
  - impi  # [win]
  - mpich  # [unix]
  - openmpi  # [unix]

channel_sources:
- conda-forge/label/llvm_rc,conda-forge   # [win]

fortran_compiler_version:
- '19'                                    # [win]